Scaler-Task-main/interview_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Scaler-Task-main/task/urls.py
from django.contrib import admin
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
from . import views

app_name = 'task'

urlpatterns = [
    path('', views.schedule_interview, name='schedule-interview'),
    path('update/<int:pk>/', views.reschedule_interview, name='reschedule-interview'),
    path('list/', views.interview_list, name='interview-list'),
    path('scheduled/', views.interview_scheduled, name='interview-scheduled'),
    path('rescheduled/', views.interview_rescheduled, name='interview-rescheduled'),
]

Scaler-Task-main/task/models.py
from django.db import models
from datetime import datetime


class Slot(models.Model):
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return str(self.date) + " " + str(self.start_time) + " - " + str(self.end_time)

    def time_object(self, o):
        start_time = o.start_time
        end_time = o.end_time
        if type(o.start_time) == str:
            try:
                start_time = datetime.strptime(o.start_time, "%H:%M").time()
            except:
                start_time = datetime.strptime(o.start_time, "%H:%M:%S").time()
        if type(o.end_time) == str:
            try:
                end_time = datetime.strptime(o.end_time, "%H:%M").time()
            except:
                end_time = datetime.strptime(o.end_time, "%H:%M:%S").time()
        return start_time, end_time


    def is_overlapping(self, o):
        start_time1, end_time1 = self.time_object(self)
        start_time2, end_time2 = self.time_object(o)
        if str(self.date) == str(o.date):
            if (start_time2 <= start_time1 and end_time2 >= start_time1) \
            or (start_time2 <= end_time1 and end_time2 >= end_time1) \
            or (start_time2 >= start_time1 and end_time2 <= end_time1) \
            or (start_time2 <= start_time1 and end_time2 >= end_time1):
                return True
            else:
                return False
        else:
            return False


class Interviewer(models.Model):
    interviewer_name = models.CharField(max_length=50)
    interviewer_email = models.EmailField(blank=True, null=True)
    scheduled_slots = models.ManyToManyField(Slot, blank=True)

    def __str__(self):
            return self.interviewer_name


class Candidate(models.Model):
    candidate_name = models.CharField(max_length=50)
    candidate_email = models.EmailField(blank=True, null=True)
    scheduled_slots = models.ManyToManyField(Slot, blank=True)
    
    def __str__(self):
        return self.candidate_name


class Interview(models.Model):
    title = models.CharField(max_length=100, default='Technical Round')
    interviewers = models.ManyToManyField(Interviewer)
    candidates = models.ManyToManyField(Candidate)
    slot = models.ForeignKey(Slot, on_delete=models.SET_NULL, null=True)
    resume = models.FileField(upload_to='resumes/', blank=True, null=True)
    
    def __str__(self):
        return str(self.id)

    def check_no_participants(self):
        return len(self.interviewers) >= 1 and len(self.candidates) >= 1

Scaler-Task-main/task/forms.py
from django import forms
from django.db.models.fields import DateField
from .models import *
# from django.contrib.auth import get_user_model
# User = get_user_model()
from django.contrib.admin.widgets import AdminDateWidget, AdminTimeWidget

class InterviewScheduleForm(forms.ModelForm):

    class Meta:
        model = Interview
        fields = ('title', 'interviewers', 'candidates', 'resume')

    def __init__(self, *args, **kwargs):
        super(InterviewScheduleForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['resume'].label = 'Resume (Optional)'
            # self.fields['patient'].queryset = User.objects.filter(user_type="P")
            # self.fields['doctor'].queryset = User.objects.filter(user_type="D")
            # self.fields["date"].label = "Date (YYYY-MM-DD)"
            # self.fields["time"].label = "Time 24 hr (HH:MM)"

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class SlotForm(forms.ModelForm):

    class Meta:
        model = Slot
        fields = ('date', 'start_time', 'end_time')
        widgets = {
            'date': DateInput(),
            'start_time': TimeInput(),
            'end_time': TimeInput(),
        }

    # def __init__(self, *args, **kwargs):
    #     super(SlotForm, self).__init__(*args, **kwargs)
        # if self.instance:
        #     self.fields['date'].widget = AdminDateWidget()
    

Scaler-Task-main/task/views.py
#Scaler SDE Internship Task Aman Babu 2019017
from django.shortcuts import render, redirect
from .forms import InterviewScheduleForm, SlotForm
from django.contrib import messages
from datetime import datetime
from django.conf import settings
from django.http import HttpResponse
from .models import Candidate, Interview, Interviewer, Slot
from django.db.models import Q
from django.core.mail import send_mail

import smtplib

# creates SMTP session
s = smtplib.SMTP('smtp.gmail.com', 587)


s.starttls()




# send interview notification email 
# def send_notification_mail(interview_obj, reschedule=False):
#     to_emails = []
#     interviewer_text = ""
#     candidate_text = ""
#     for i in interview_obj.interviewers.all():
#         interviewer_text += i.interviewer_name + ", "
#         if i.interviewer_email:
#             to_emails.append(i.interviewer_email)
#     for i in interview_obj.candidates.all():
#         candidate_text += i.candidate_name + ", "
#         if i.candidate_email:
#             to_emails.append(i.candidate_email)
#     opening_line = 'An interview has been scheduled and details are mentioned below - '
#     subject = 'Interview Scheduled!'
#     if reschedule:
#         opening_line = 'Your interview has been rescheduled and details are mentioned below - '
#         subject = 'Interview Rescheduled!'
    # print(to_emails, interviewer_text, candidate_text, opening_line)
    # message = f"""Hi,

# {opening_line} 
# Title: {interview_obj.title}
# Date: {interview_obj.slot.date}
# Time: {interview_obj.slot.start_time} - {interview_obj.slot.end_time}
# Interviewer(s): {interviewer_text}
# Candidate(s):  {candidate_text}

# Regards
# Interview Creation Portal Team"""
#     # print(message)
#     send_mail(subject, message, settings.EMAIL_HOST_USER, to_emails)


# interviews list function 
def interview_list(request):
    curr_date_obj = datetime.now().date()
    curr_time_obj = datetime.now().time()
    interviews = Interview.objects.filter(Q(slot__date__gt=curr_date_obj) | (Q(slot__date=curr_date_obj) & Q(slot__start_time__gte=curr_time_obj)))
    interviews = interviews.order_by('slot__date', 'slot__start_time')
    context = {"interviews": interviews}
    return render(request, 'task/interview_list.html', context=context)


# check availability
def check_availability(slot_obj, interviewers, candidates):
    # print(slot_obj, interviewers, candidates)
    flag = False
    message_text = ""
    for i in interviewers:
        i_obj = Interviewer.objects.get(id=i)
        # print(i_obj, i_obj.scheduled_slots.all())
        for j in i_obj.scheduled_slots.all():
            if slot_obj.is_overlapping(j):
                # print('hi1')
                message_text += i_obj.interviewer_name + ", "
                flag = True
    for i in candidates:
        i_obj = Candidate.objects.get(id=i)
        # print(i_obj, i_obj.scheduled_slots.all())
        for j in i_obj.scheduled_slots.all():
            if slot_obj.is_overlapping(j):
                # print('hi2')
                message_text += i_obj.candidate_name + ", "
                flag = True
    return flag, message_text


# add current slot to interviewers and candidates
def add_slot(slot_obj, interview_obj, interviewers, candidates):
    for i in interviewers:
        i_obj = Interviewer.objects.get(id=i)
        interview_obj.interviewers.add(i_obj)
        i_obj.scheduled_slots.add(slot_obj)
    for i in candidates:
        i_obj = Candidate.objects.get(id=i)
        interview_obj.candidates.add(i_obj)
        i_obj.scheduled_slots.add(slot_obj)


# remove previous slot from interviewers and candidates
def remove_slot(prev_slot_obj, interview_obj):
    for i in interview_obj.interviewers.all():
        i.scheduled_slots.remove(prev_slot_obj)
    for i in interview_obj.candidates.all():
        i.scheduled_slots.remove(prev_slot_obj)
    interview_obj.interviewers.clear()
    interview_obj.candidates.clear()

# def index(request):
#     message = "Test -1"
 
#     # sending the mail
#     s.sendmail("senorita4488@gmail.com", "2019017@iiitdmj.ac.in", message)
    
#     # terminating the session
#     s.quit()
# interview schedule function
def schedule_interview(request):

    if request.method == "POST":
        title = request.POST['title']
        interviewers = dict(request.POST)['interviewers']
        candidates = dict(request.POST)['candidates']
        # if(not candidates and not interviewers ):
        #     messages.error(request, 'Less than 1')
        date = request.POST['date']
        start_time = request.POST['start_time']
        end_time = request.POST['end_time']
        print(request.FILES, request.POST)
        # print(5 / 0)
        interview_form = InterviewScheduleForm(request.POST, request.FILES)
        slot_form = SlotForm(request.POST, request.FILES)
        date_obj = datetime.strptime(request.POST['date'], "%Y-%m-%d").date()
        try:
            start_time_obj = datetime.strptime(start_time, "%H:%M").time()
        except:
            start_time_obj = datetime.strptime(start_time, "%H:%M:%S").time()
        try:
            end_time_obj = datetime.strptime(end_time, "%H:%M").time()
        except:
            end_time_obj = datetime.strptime(end_time, "%H:%M:%S").time()
        curr_date_obj = datetime.now().date()
        curr_time_obj = datetime.now().time()
        
        # My Name is Aman
        
        if not (start_time_obj <= end_time_obj and 
        (date_obj > curr_date_obj or (date_obj == curr_date_obj and start_time_obj >= curr_time_obj))):
            messages.error(request, 'Invalid Date, Start time or End time! Please Try Again')
        else:
            slot_obj = Slot.objects.get_or_create(date=date, start_time=start_time, end_time=end_time)[0]
            # print(slot_obj, interviewers, candidates)
            flag, message_text = check_availability(slot_obj, interviewers, candidates)
            # print(flag, message_text)
            if flag:
                messages.error(request, message_text + 'are not available at this slot! Please try for different Slot')
            else:
                try:
                    resume = request.FILES['resume']
                    interview_obj = Interview.objects.create(title=title, slot=slot_obj, resume=resume)
                except:    
                    interview_obj = Interview.objects.create(title=title, slot=slot_obj)
                add_slot(slot_obj, interview_obj, interviewers, candidates)
                interview_obj.save()
                print("check-1",interview_obj.interviewers)
                # send_mails([interview_obj.interviewers],"Testing")
                # print(interviewers, candidates)
                # send_notification_mail(interview_obj)
                return redirect('task:interview-scheduled')
    else:
        interview_form = InterviewScheduleForm()
        slot_form = SlotForm()
    
    return render(request, 'task/index.html', {'interview_form': interview_form, 'slot_form': slot_form})


def reschedule_interview(request, pk):
    interview_obj = Interview.objects.get(id=pk)
    prev_slot_obj = interview_obj.slot
    if request.method == "POST":
        title = request.POST['title']
        interviewers = dict(request.POST)['interviewers']
        candidates = dict(request.POST)['candidates']
        date = request.POST['date']
        start_time = request.POST['start_time']
        end_time = request.POST['end_time']
        interview_form = InterviewScheduleForm(request.POST, request.FILES)
        slot_form = SlotForm(request.POST, request.FILES)
        # print(start_time, end_time, date)
        date_obj = datetime.strptime(request.POST['date'], "%Y-%m-%d").date()
        try:
            start_time_obj = datetime.strptime(start_time, "%H:%M").time()
        except:
            start_time_obj = datetime.strptime(start_time, "%H:%M:%S").time()
        try:
            end_time_obj = datetime.strptime(end_time, "%H:%M").time()
        except:
            end_time_obj = datetime.strptime(end_time, "%H:%M:%S").time()
        curr_date_obj = datetime.now().date()
        curr_time_obj = datetime.now().time()
        # print(date_obj, start_time_obj, end_time_obj)
        # print(end_time_obj < start_time_obj)
        # print(date_obj < datetime.now().date() )
        # print(start_time_obj < datetime.now().time())
        if not (start_time_obj <= end_time_obj and 
        (date_obj > curr_date_obj or (date_obj == curr_date_obj and start_time_obj >= curr_time_obj))):
            messages.error(request, 'Invalid Date, Start time or End time')
        else:
            slot_obj = Slot.objects.get_or_create(date=date, start_time=start_time, end_time=end_time)[0]
            remove_slot(prev_slot_obj, interview_obj)
            flag, message_text = check_availability(slot_obj, interviewers, candidates)
            if flag:
                messages.error(request, message_text + 'are not available at this slot! Please check for another slot')
            else:
                try:
                    resume = request.FILES['resume']
                    interview_obj.resume = resume
                except:
                    pass
                interview_obj.title = title
                interview_obj.slot = slot_obj
                add_slot(slot_obj, interview_obj, interviewers, candidates)
                interview_obj.save()
                # send_notification_mail(interview_obj, True)
                
                send_mails([interview_obj.interviewer_email],"Testing")
                return redirect('task:interview-rescheduled')
    else:
        interview_form = InterviewScheduleForm(instance=interview_obj)
        slot_form = SlotForm(instance=prev_slot_obj)
    return render(request, 'task/interview_update.html', {'interview_form': interview_form, 'slot_form': slot_form})    


# interview scheduled function
def interview_scheduled(request):
    

Scaler-Task-main/templates/task/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <title>Interview Creation Portal (ICP)</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
        integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
        crossorigin="anonymous"></script>


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>

<body style="padding: 0px 300px;">
    <nav class="container rounded navbar navbar-expand-lg navbar-dark bg-dark">
        <!-- navbar navbar-light bg-light -->
        <div class="container">
            <a class="navbar-brand " href="{% url 'task:schedule-interview' %}">Interview Creation Portal (ICP)</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item active mynav">
                        <a class="nav-link" href="{% url 'task:schedule-interview' %}">Schedule <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active mynav">
                        <a class="nav-link" href="{% url 'task:interview-list' %}">Interview List <span
                                class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% for message in messages %}
    <div class="container-fluid p-0">
        <div class="alert {{ message.tags }} alert-dismissible mymessages" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="True">&times;</span>
            </button>
            {{ message }}
        </div>
    </div>
    {% endfor %}

    {% block content %}

    {% endblock %}
</body>

<!-- <script src="{% static 'js/script.js' %}"> </script> -->

</html>

Scaler-Task-main/templates/task/index.html
{% extends "task/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load bootstrap4 %}

<div class="container mycontent">

    <form class="myform" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form interview_form %}
        {% bootstrap_form slot_form %}
        <input type="submit" value="Schedule" class="btn btn-success">
    </form>
</div>

{% endblock %}

Scaler-Task-main/templates/task/interview_list.html
{% extends "task/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load bootstrap4 %}
<div class="container myinterviews">
    <h2 style="text-align: center; padding: 15px;">Upcoming Interviews</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Interviewers</th>
                <th scope="col">Candidates</th>
                <th scope="col">Date</th>
                <th scope="col">Start time</th>
                <th scope="col">End time</th>
                <th scope="col">Resume</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in interviews %}
            <tr>
                <th scope="row">{{obj.id}}</th>
                <td>{{obj.title}}</td>
                <td>
                    {% for i in obj.interviewers.all %}
                    {{i.interviewer_name}},
                    {% endfor %}
                </td>
                <td>
                    {% for i in obj.candidates.all %}
                    {{i.candidate_name}}, 
                    {% endfor %}
                </td>
                <td>{{obj.slot.date}}</td>
                <td>{{obj.slot.start_time}}</td>
                <td>{{obj.slot.end_time}}</td>
                <td>
                    {% if obj.resume %}
                    <a href="https://scaler-task.herokuapp.com/media/{{obj.resume}}" target='_blank'>Resume's link</a>
                    {% else %}
                    N/A
                    {% endif %}                    
                </td>
                <td><a href="{% url 'task:reschedule-interview' pk=obj.id %}"><button class="btn btn-primary">Update</button></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Scaler-Task-main/templates/task/interview_rescheduled.html
{% extends "task/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load bootstrap4 %}

<div class="container mycontent">
    <h1>The Interview has been Successfully rescheduled!</h1>
</div>

{% endblock %}

Scaler-Task-main/templates/task/interview_scheduled.html
{% extends "task/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load bootstrap4 %}

<div class="container mycontent">
    <h1>The Interview has been Successfully Scheduled!</h1>
</div>

{% endblock %}

Scaler-Task-main/templates/task/interview_update.html
{% extends "task/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load bootstrap4 %}

<div class="container mycontent">

    <form class="myform" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form interview_form %}
        {% bootstrap_form slot_form %}
        <input type="submit" value="Reschedule" class="btn btn-success">
    </form>
</div>

{% endblock %}